import os
import time
from typing import List
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate

# ================= 配置区 =================
OUTPUT_FILE = r"e:\rag_project\data\supplement\water_acoustic_concepts_500.txt"
TOTAL_CONCEPTS = 500
# 你的 API Key
API_KEY = "sk-3034bf5ffdb84bb291bff7f41cd1d302" 
MODEL_NAME = "qwen-plus"

# 定义细分领域 (Sub-domains) 以确保内容多样性
# 减少领域数量，每个领域生成 25 条，共 20 * 25 = 500
DOMAINS = [
    "水声物理基础与传播公式 (声速、声压、传播损失计算)",
    "海洋环境噪声模型与计算 (Wenz曲线、风速噪声级)",
    "声纳方程与性能估算 (SL、TL、TS、NL、DI、DT计算)",
    "声纳基阵设计与参数计算 (阵增益、波束宽度、指向性)",
    "水声信号处理算法公式 (多普勒频移、模糊度、匹配滤波)",
    "目标强度与回声特性计算 (球体、圆柱体TS计算)",
    "混响模型与统计特性 (海面/海底/体积混响强度计算)",
    "水声通信链路预算与信道 (信噪比、误码率、信道容量)",
    "水声定位与导航算法 (LBL/SBL/USBL解算公式)",
    "水声换能器参数计算 (灵敏度、发送响应、阻抗匹配)",
    "深海声学与声影区计算 (声线轨迹、汇聚区距离)",
    "浅海简正波与截止频率 (截止频率计算、模态数)",
    "水声对抗与干扰效能 (干扰方程、信干比J/S)",
    "潜艇辐射噪声源级估算 (机械噪声、螺旋桨噪声谱级)",
    "流噪声与水动力学计算 (边界层压力起伏、流噪声级)",
    "声吸收与衰减系数计算 (Thorpe公式、吸收系数alpha)",
    "多途效应与信道冲激响应 (时延差、多径强度)",
    "合成孔径声纳SAS原理 (方位分辨率、合成孔径长度)",
    "目标运动分析TMA (纯方位定位、卡尔曼滤波方程)",
    "海洋声学反演与层析 (声速剖面反演、地声参数)"
]

# ================= 初始化 LLM =================
llm = ChatOpenAI(
    api_key=API_KEY,
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
    model=MODEL_NAME,
    temperature=0.7, # 稍微增加创造性
    max_tokens=2048
)

# ================= Prompt 设计 =================
# 关键：要求输出格式非常规范，方便后续正则提取
template = """
你是水声工程领域的顶级专家。请针对【{domain}】这一细分领域，生成 {count} 条核心概念或计算公式。

【非常重要的格式要求】：
为了便于后续RAG系统自动清洗和切分，请严格遵守以下 Markdown 格式。每一条概念之间用 "---" 分隔。

### 概念名称 (英文名称)
**定义**: 详细的定义描述，包含物理意义...
**计算公式**: (如果有公式，请尽量用 Python 表达式风格，例如 `TL = 20 * log10(r)`，变量名用英文或通用符号。如果没有公式则写"无")
**关键变量**:
- 变量1: 含义...
- 变量2: 含义...
**应用**: 在工程中的具体应用...

---

【内容要求】：
1. 概念必须属于“{domain}”领域。
2. **优先生成带有计算公式的概念**（如传播损失、声速、噪声级、阵增益等）。
3. 解释要专业、深入。
4. **禁止使用 LaTeX 格式**（如 `$$`, `\frac`），公式必须用类似 Python 代码的可读形式（如 `c = 1449.2 + 4.6 * T`）。
5. 确保不重复。

【输出数量】：必须生成 {count} 条。

【开始生成】：
"""

prompt = PromptTemplate(
    template=template,
    input_variables=["domain", "count"]
)

chain = prompt | llm

# ================= 主程序 =================

def generate_concepts():
    print(f"🚀 开始生成 500 条水声工程概念库 (含计算公式)...")
    print(f"📂 输出文件: {OUTPUT_FILE}")
    
    # 确保目录存在
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    # 写入文件头
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("# 水声工程 500 条核心概念与公式库 (Generated by AI)\n")
        f.write("# 格式优化：Markdown + Python风格公式\n\n")
        f.write(f"> 生成时间: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"> 包含领域: {len(DOMAINS)} 个专业方向\n\n")

    total_generated = 0
    
    for i, domain in enumerate(DOMAINS):
        print(f"\n[{i+1}/{len(DOMAINS)}] 正在生成领域: {domain} ...")
        
        try:
            # 每个领域生成 25 条 (20个领域 * 25 = 500)
            response = chain.invoke({
                "domain": domain,
                "count": 25
            })
            
            content = response.content
            
            # 写入文件
            with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
                f.write(f"\n\n## 领域 {i+1}: {domain}\n")
                f.write("-" * 50 + "\n")
                f.write(content)
                f.write("\n")
            
            # 简单统计生成数量 (通过 ### 计数)
            count = content.count("### ")
            total_generated += count
            print(f"  ✅ 完成! 本次生成约 {count} 条。总进度: {total_generated}/500")
            
            # 避免 API 速率限制，休眠 2 秒
            time.sleep(2)
            
        except Exception as e:
            print(f"  ❌ 生成失败: {e}")
            # 简单的重试机制或跳过
            continue

    print(f"\n🎉 所有任务完成！共生成约 {total_generated} 条概念。")
    print(f"请查看文件: {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_concepts()
